import Head from "next/head";
import React, { useEffect } from "react";

type CallbackProps = {};

const Callback: React.FC<CallbackProps> = () => {
  useEffect(() => {
    if (window.opener && window.opener.location.pathname === "/auth/login") {
      window.opener.location.replace("/home");
    } else {
      window.location.replace("/home");
    }

    if (window.opener) {
      window.close();
    }
  });

  return (
    <>
      <Head>
        <title>Holoverse | Better Spaces for Online Events </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        />
      </Head>
      <div className="w-screen h-screen flex items-center justify-center">
        Please Wait ...{" "}
      </div>
    </>
  );
};

export default Callback;
