import { api } from "@/api";
import AppDialog from "@/components/global/AppDialog";
import { withProtectedRoute } from "@/components/global/ProtectedRoute";
import { HomeDeviceIssue } from "@/components/home/HomeDeviceIssue";
import { HomeGrid } from "@/components/home/HomeGrid";
import { HomeLayout } from "@/components/home/HomeLayout";
import { HomeNav } from "@/components/home/HomeNav";
import { HomeOptionsBar } from "@/components/home/HomeOptionsBar";
import { HomeRoomPreviewCard } from "@/components/home/HomeRoomPreviewCard";
import { useRoomStore } from "@/global-store/RoomStore";
import { useSettingStore } from "@/global-store/SettingStore";
import { useUIStore } from "@/global-store/UIStore";
import { useQuery } from "@tanstack/react-query";
import { NextPage } from "next";
import Head from "next/head";
import React from "react";

const Home: NextPage = () => {
  const [activeTab, setActiveTab] = React.useState("spaces");
  const [activeFilter, setActiveFilter] = React.useState("public");
  const [filterQuery, setFilterQuery] = React.useState("");
  const { set, sheetOpen } = useUIStore();
  const { hasCameraIssue, hasMicIssue, hasSpeakerIssue } = useSettingStore();

  const { data: publicRooms, isLoading: publicRoomsLoading } = useQuery({
    queryKey: ["rooms-public"],
    queryFn: async () => {
      try {
        const { data } = await api.get(`/room/rooms/live`);
        return data;
      } catch (error) {
        console.log(error);
      }
    },
  });

  const hasDeviceIssue = hasCameraIssue || hasMicIssue || hasSpeakerIssue;

  return (
    <>
      <Head>
        <title>Holoverse | Better Spaces for Online Events </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        />
      </Head>

      <main
        className={`w-screen h-auto bg-[#202225] font-logo flex justify-center py-5 page-content ${
          sheetOpen ? "shifted" : ""
        }`}
      >
        <AppDialog
          open={hasDeviceIssue}
          width={"sm:max-w-[400px] p-0"}
          dontShowClose
          content={<HomeDeviceIssue />}
        >
          <></>
        </AppDialog>
        <HomeLayout
          navbar={<HomeNav activeTab={activeTab} setActiveTab={setActiveTab} />}
          content={
            activeTab === "spaces" ? (
              <HomeGrid
                filterQuery={filterQuery}
                rooms={publicRooms}
                roomsLoading={publicRoomsLoading}
              />
            ) : (
              <>
                <div className="flex w-full h-full justify-center items-center">
                  Coming Soon✨
                </div>
              </>
            )
          }
          optionbar={
            <HomeOptionsBar
              activeFilter={activeFilter}
              setActiveFilter={setActiveFilter}
              filterQuery={filterQuery}
              setFilterQuery={setFilterQuery}
            />
          }
        />
      </main>
    </>
  );
};

export default withProtectedRoute(Home);
