import { LandingPage } from "@/components/global/LandingPage";
import { Logo } from "@/components/global/Logo";
import { Separator } from "@/components/ui/separator";
import { Button } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import router, { useRouter } from "next/router";
import { useEffect } from "react";

const Update: NextPage = () => {
  return (
    <>
      <Head>
        {" "}
        <title>Holoverse | Better Spaces for Online Events </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        />
      </Head>

      <main
        className={`w-screen h-screen bg-[#202225] font-logo flex flex-col  page-content`}
      >
        <nav className="flex w-full justify-center px-40 z-10 py-10 h-16 items-center">
          <div className="w-full flex flex-1 justify-between items-center">
            <span
              className="flex items-center gap-2"
              onClick={async () => {
                await router.push("/home");
              }}
            >
              <Logo withLogo={true} withText={false} size="md" />
              <Separator orientation="vertical" className="bg-light h-5" />
              <span className="opacity-50 text-[16px]">News & Updates</span>
            </span>
            <div className="flex gap-4">
              <div className="flex items-center gap-6">
                <button
                  onClick={async () => {
                    await router.push("/home");
                  }}
                  className="flex items-center "
                >
                  <span className="font-new text-appGreen">
                    {" "}
                    Back to Holoverse
                  </span>
                </button>
              </div>
            </div>
          </div>
        </nav>
        <Separator className="bg-red-50" orientation="horizontal" />
        <section className="w-1/3 text-[1.2rem] flex flex-col items-center justify-center mx-auto mt-10">
          <span className="text-appYellow border-b border-1 mb-10 border-appYellow">
            News
          </span>
          <div className="flex flex-col items-center">
            <span>
              <span className="text-[45px]  font-new">Holoverse is Live !</span>
            </span>
            <span className="text-[15px] opacity-50">- by Team Holoverse</span>
            <section className="mt-10 font-sans leading-[2.4rem] opacity-80">
              <p className="py-3">
                Holoverse is now open to everyone, along with a new homepage and
                public demo showing how it works. Anyone and everyone can now
                create their own world, start editing, and invite others to join
                you.
              </p>
              <p className="py-3">
                Huge thanks to all the beta testers, event organizers, and
                creators who used Holoverse over the last few months, letting us
                see what worked and what doesn’t. Your continued feedback keeps
                making it better.
              </p>
              <p className="py-3">
                We have a bunch of fun stuff lined up for the next couple weeks,
                some teased in the demo, so keep an eye out. We’re so excited to
                share it with you.
              </p>
              <a
                href="/home"
                className="text-[15px] font-bold underline text-appGreen"
              >
                GO GO GO!
              </a>
            </section>
          </div>
        </section>
      </main>
    </>
  );
};

export default Update;
