name: Holoverse CD

on:
  pull_request:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files to remote
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          source: "."
          target: "~/home/${{ secrets.REMOTE_USERNAME }}/app"

      - name: Install Docker and Docker Compose on remote if not exist
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          script: |
            if ! command -v docker &> /dev/null
            then
              sudo apt-get update
              sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
              sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
              sudo apt-get update
              sudo apt-get install -y docker-ce
              sudo usermod -aG docker $USER
              newgrp docker
            fi
            if ! command -v docker-compose &> /dev/null
            then
              sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi

      - name: Install mediasoup build essentials and pnpm on remote
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          script: |
            sudo apt-get update
            sudo apt-get install -y build-essential python3
            sudo npm install -g pnpm
            cd ~/home/${{ secrets.REMOTE_USERNAME }}/app/webrtc-server
            export NODE_ENV=production
            pnpm install

      - name: Give execute permissions and run install_ssl script on remote
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          script: |
            cd ~/home/${{ secrets.REMOTE_USERNAME }}/app
            chmod +x scripts/install_ssl.sh
            docker-compose --env-file .env.production build
            pm2 kill

      - name: Run Docker Compose on remote
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          script: cd ~/home/${{ secrets.REMOTE_USERNAME }}/app; rm -rf frontend previews; chmod +x ./scripts/start_prod.sh; ./scripts/start_prod.sh
